# Generated by Django 4.0 on 2021-12-31 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_category_alter_post_author_alter_post_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(default='Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque mauris justo, dignissim ut orci ac, scelerisque egestas nulla. Donec placerat vel urna a porttitor. Nam tempus neque id diam posuere, at ornare ipsum tincidunt. Proin ut dui id arcu auctor faucibus sed in eros. Nam sit amet massa tincidunt, pellentesque nisi non, consectetur felis. Sed aliquet hendrerit magna nec mattis. Maecenas gravida metus a luctus scelerisque. Quisque nisl purus, hendrerit et aliquam in, bibendum et neque. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Interdum et malesuada fames ac ante ipsum primis in faucibus. Fusce non tempus orci. Aliquam pulvinar dolor sed risus faucibus gravida. ', verbose_name='descripció'),
            preserve_default=False,
        ),
    ]
