# Generated by Django 4.0 on 2021-12-31 17:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200, verbose_name='nom')),
                ('last_name', models.CharField(max_length=200, verbose_name='cognoms')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nom')),
                ('acronym', models.CharField(max_length=200, verbose_name='sigles')),
            ],
        ),
        migrations.CreateModel(
            name='Bocamoll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='text')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='data')),
                ('aproved', models.FloatField(default=False, verbose_name='estat')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bocamolls.professor', verbose_name='professor')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bocamolls.subject', verbose_name='subject')),
            ],
        ),
    ]
