# Generated by Django 4.0 on 2021-12-31 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bocamolls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bocamoll',
            name='aproved',
            field=models.BooleanField(default=False, verbose_name='estat'),
        ),
    ]
