# Generated by Django 4.0 on 2021-12-31 17:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bocamolls', '0002_alter_bocamoll_aproved'),
    ]

    operations = [
        migrations.AddField(
            model_name='bocamoll',
            name='creation',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='bocamoll',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bocamolls.subject', verbose_name='assignatura'),
        ),
    ]
